/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package id.jasoet.auth

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        assertNotNull(App.greeting, "app should have a greeting")
    }
}
